### PR TITLE
Add rewritten 'wldd' and autotools support.

### PR DESCRIPTION
**Pull request by nihilus**
I did cleaned it up and ended up with these 2 commits only.

### CODE REVIEW

**Comment by endrazine** [comment]
Amazing ! Let me merge this over the week end :)
Thanks !

**Comment by nihilus** [comment]
You are welcome... I found myself using wldd, as of yesterday at working when comparing linkage with a coworker... Note that I did change '-libify' to a long option, '--libify'.

**Comment by rofl0r** [comment]
good work! just a small note, usually autoconf-generated files like "configure" or "config.sub" are not checked into git repos, so the repo is not cluttered. otoh this puts the additional burden that you need autoconf/automake installed on people wanting to check out the code from git. so there's pros and cons for each approach.

**Comment by nihilus** [comment]
You have never been responsible for releases on ftp.gnu.org I hear... How would end-users be aböe to run things without the configure script itself? If this is some sort of github thing going on, then things need to change into a more userfriemdly way.

**Comment by rofl0r** [comment]
well, i'm just commenting on common practice, not on personal preferences :)
and what i've seen so far is that most projects ship only configure.ac and autogen.sh and leave it to the person checking out the repo to run autogen.sh. in such a case it is necessary to at least generate the configure scripts as part of the `make dist` workflow when creating a tarball, but some projects don't even do that, and that's when [things get nasty](https://github.com/sabotage-linux/sabotage/wiki/Why-github-downloads-suck).

so, what's the thing with india you're refering to ?

**Comment by nihilus** [comment]
Interesting and I admit I am old fashioned...;-)
Well, since 95% of India's IT-sector cannot code at all (and probably 2/3 of the remaining 5% was lucky their "cargo cult programming" passed):
https://slashdot.org/story/325199

**Comment by endrazine** [comment]
Hello Nihilus,

I don't manage to configure the project:

	jonathan@blackbox:/tmp/nihilus/wcc$ git log|head -n 3
	commit 80e6ee114dc8fad95d42de6e4a4625f7fe4da432
	Author: Markus Gothe <nietzsche@lysator.liu.se>
	Date:   Thu May 11 18:25:01 2017 +0200
	jonathan@blackbox:/tmp/nihilus/wcc$ 
	jonathan@blackbox:/tmp/nihilus/wcc$ git submodule update && git submodule update 
	jonathan@blackbox:/tmp/nihilus/wcc$
	jonathan@blackbox:/tmp/nihilus/wcc$ ./configure 
	...
	checking for cs_version in -lcapstone... yes
	checking bfd.h usability... yes
	checking bfd.h presence... yes
	checking for bfd.h... yes
	checking for bfd_init in -lbfd... yes
	checking for get_run_time in -liberty... yes
	checking openlibm.h usability... no
	checking openlibm.h presence... no
	checking for openlibm.h... no
	checking for isopenlibm in -lopenlibm... no
	configure: error: Unable to find the isopenlibm() function!
	jonathan@blackbox:/tmp/nihilus/wcc$ 


Running autogen.sh doesn't solve the problem. Any advise ?

j-

**Comment by endrazine** [comment]
The config.log shows:

	configure:17677: checking openlibm.h usability
	configure:17677: gcc -c -g -O2  conftest.c >&5
	conftest.c:84:22: fatal error: openlibm.h: No such file or directory
	compilation terminated.

Now, we ship openlibm as a git submodule right ? Isn't there a missing path to the openlibm includes here ?

**Comment by nihilus** [comment]
Maybe I should integrate openlibm in the build system as well, if you have it installed on the system everything will work.

**Comment by endrazine** [comment]
I mean, we ship it ! Yeah, we nees to be able to build it too :))

**Comment by endrazine** [comment]
I still can't compile mate : there's a dependency problem. I agree that if I install openlibm separately, then it works. Any chance you fix this before we merge ?
Thanks.

**Comment by endrazine** [comment]
I also have an issue with the Copyright notice in your Makefiles : do you mind releasing them as MIT or BSD to be coherent with existing licenses ?

**Comment by endrazine** [comment]
Merged manually :)

Thanks heaps for your contribution !

**Pull request closed without merging**
